<?php
/*
JSON_SQL_Bridge 1.0
Copyright 2016 Frank Vanden berghen
All Right reserved.

JSON_SQL_Bridge is not a free software. The JSON_SQL_Bridge software is NOT licensed under the "Apache License". 
If you are interested in distributing, reselling, modifying, contibuting or in general creating 
any derivative work from JSON_SQL_Bridge, please contact Frank Vanden Berghen at frank@timi.eu.
*/
namespace kibella; require_once "constantscfg.php"; function lc($Oe,$Ob="/\t+/") { $lf=array(); if (($Of=fopen($Oe,"r")) === FALSE) throw new exception( __FUNCTION__."Cannot open configuration file ($Oe)."); while (($lg=fgets($Of,02000)) !== FALSE) { $lg=preg_replace("/(^\\s+)|(\\s+\$)/","",$lg); if (preg_match("/^#/",$lg) == 0) { $Og=preg_split($Ob,$lg); if (count($Og)>1) { $lf[$Og[0]]=trim($Og[1]); } } } return $lf; } function l12($Oe=APPCONFIG,$Ob="/\t+/") { $lf=lc($Oe,$Ob); foreach ($lf as $l4w => $l3c) { $l4w=trim(strtoupper( "$l4w")); if ($l4w === "CACHEMODE" || $l4w === "CACHEDAYCHANGE" || $l4w === "CACHEHOURS" || $l4w === "DATADIR" || $l4w === "DISCOVERSIZE" || $l4w === "ADDTABLEPREFIX" || $l4w === "LISTONLYTABLEOBJECTS" || $l4w === "ACCELERATETOP" || $l4w === "ACCELERATEMAX" || $l4w === "DBCONNECTIONSFILE" || $l4w === "MULTITHREADING") { if ($l4w === "DATADIR" && stripos(trim($l3c),"..") == 0) { $l3c= __DIR__."/../".trim($l3c); } define(__NAMESPACE__."\\".$l4w,$l3c); } } if (!defined(__NAMESPACE__."\\DATADIR"))define(__NAMESPACE__."\\DATADIR",DEFAULT_DATADIR); if (!defined(__NAMESPACE__."\\DISCOVERSIZE")) { define(__NAMESPACE__."\\DISCOVERSIZE",O2v); } if (!defined(__NAMESPACE__."\\ADDTABLEPREFIX"))define(__NAMESPACE__."\\ADDTABLEPREFIX",l2w); if (!defined(__NAMESPACE__."\\LISTONLYTABLEOBJECTS"))define(__NAMESPACE__."\\LISTONLYTABLEOBJECTS",O2w); if (!defined(__NAMESPACE__."\\CACHEMODE"))define(__NAMESPACE__."\\CACHEMODE",l2x); if (!defined(__NAMESPACE__."\\CACHEDAYCHANGE"))define(__NAMESPACE__."\\CACHEDAYCHANGE",O2x); if (!defined(__NAMESPACE__."\\CACHEHOURS"))define(__NAMESPACE__."\\CACHEHOURS",l2y); if (!defined(__NAMESPACE__."\\ACCELERATETOP"))define(__NAMESPACE__."\\ACCELERATETOP",l2z); if (!defined(__NAMESPACE__."\\ACCELERATEMAX"))define(__NAMESPACE__."\\ACCELERATEMAX",O2y); if (!defined(__NAMESPACE__."\\DBCONNECTIONSFILE"))define(__NAMESPACE__."\\DBCONNECTIONSFILE",DEFAULT_DBCONNECTIONSFILE); if (!defined(__NAMESPACE__."\\MULTITHREADING"))define(__NAMESPACE__."\\MULTITHREADING",O2z); }