<?php
/*
JSON_SQL_Bridge 1.0
Copyright 2016 Frank Vanden berghen
All Right reserved.

JSON_SQL_Bridge is not a free software. The JSON_SQL_Bridge software is NOT licensed under the "Apache License". 
If you are interested in distributing, reselling, modifying, contibuting or in general creating 
any derivative work from JSON_SQL_Bridge, please contact Frank Vanden Berghen at frank@timi.eu.
*/
namespace kibella; require_once "constantscfg.php"; function lc($Oe,$Ob="/\t+/") { $lf=array(); if (($Of=fopen($Oe,"r")) === FALSE) throw new exception( __FUNCTION__."Cannot open configuration file ($Oe)."); while (($lg=fgets($Of,02000)) !== FALSE) { $lg=preg_replace("/(^\\s+)|(\\s+\$)/","",$lg); if (preg_match("/^#/",$lg) == 0) { $Og=preg_split($Ob,$lg); if (count($Og)>1) { $lf[$Og[0]]=trim($Og[1]); } } } return $lf; } function l13($Oe=APPCONFIG,$Ob="/[\t ]+/") { $lf=lc($Oe,$Ob); foreach ($lf as $O4z => $O3c) { $O4z=trim(strtoupper( "$O4z")); if ($O4z === "CACHEMODE" || $O4z === "CACHEDAYCHANGE" || $O4z === "CACHEHOURS" || $O4z === "DATADIR" || $O4z === "DISCOVERSIZE" || $O4z === "ADDTABLEPREFIX" || $O4z === "LISTONLYTABLEOBJECTS" || $O4z === "ACCELERATETOP" || $O4z === "ACCELERATEMAX" || $O4z === "DBCONNECTIONSFILE" || $O4z === "MULTITHREADING") { if ($O4z === "DATADIR" && stripos(trim($O3c),"..") == 0) { $O3c= __DIR__."/../".trim($O3c); } define(__NAMESPACE__."\\".$O4z,$O3c); } } if (!defined(__NAMESPACE__."\\DATADIR"))define(__NAMESPACE__."\\DATADIR",DEFAULT_DATADIR); if (!defined(__NAMESPACE__."\\DISCOVERSIZE")) { define(__NAMESPACE__."\\DISCOVERSIZE",l2w); } if (!defined(__NAMESPACE__."\\ADDTABLEPREFIX"))define(__NAMESPACE__."\\ADDTABLEPREFIX",O2w); if (!defined(__NAMESPACE__."\\LISTONLYTABLEOBJECTS"))define(__NAMESPACE__."\\LISTONLYTABLEOBJECTS",l2x); if (!defined(__NAMESPACE__."\\CACHEMODE"))define(__NAMESPACE__."\\CACHEMODE",O2x); if (!defined(__NAMESPACE__."\\CACHEDAYCHANGE"))define(__NAMESPACE__."\\CACHEDAYCHANGE",l2y); if (!defined(__NAMESPACE__."\\CACHEHOURS"))define(__NAMESPACE__."\\CACHEHOURS",O2y); if (!defined(__NAMESPACE__."\\ACCELERATETOP"))define(__NAMESPACE__."\\ACCELERATETOP",O2z); if (!defined(__NAMESPACE__."\\ACCELERATEMAX"))define(__NAMESPACE__."\\ACCELERATEMAX",l2z); if (!defined(__NAMESPACE__."\\DBCONNECTIONSFILE"))define(__NAMESPACE__."\\DBCONNECTIONSFILE",DEFAULT_DBCONNECTIONSFILE); if (!defined(__NAMESPACE__."\\MULTITHREADING"))define(__NAMESPACE__."\\MULTITHREADING",l30); }