<?php
/*
JSON_SQL_Bridge 1.0
Copyright 2016 Frank Vanden berghen
All Right reserved.

JSON_SQL_Bridge is not a free software. The JSON_SQL_Bridge software is NOT licensed under the "Apache License". 
If you are interested in distributing, reselling, modifying, contibuting or in general creating 
any derivative work from JSON_SQL_Bridge, please contact Frank Vanden Berghen at frank@timi.eu.
*/
namespace kibella; function l88($O4t,$O88,$l89,$O3a,$O89=0) { if (DEBUG && l8a($O88,$l89) && array_search($O4t,$l89[$O88]) == FALSE) { if ($O89 == 0) { echo "WARNING: (".strtoupper($O3a)."): Invalid keyword '$O4t' for context '$O88'!\n"; } if ($O89 == 1) { echo "WARNING: (".strtoupper($O3a)."): Invalid keyword '$O4t' for context '$O88'! Previous context is maintained.\n"; } else if ($O89 == 2) { echo "WARNING: (".strtoupper($O3a)."): Invalid keyword '$O4t' for context '$O88'! The process may generate unexpected results.\n"; } } } function O8a($O88,$O3a) { if (DEBUG) { echo "WARNING: (".strtoupper($O3a)."): Invalid context '$O88'!\n"; } } function O77($O55) { if (DEBUG) { echo "WARNING: Invalid metadata type ('$O55') for the currently used database!\n"; echo "         Field type set to STRING.\n"; } } function l8b($O55) { if (DEBUG) { echo "WARNING: Invalid aggregation type ('$O55'). No action will be taken on the aggregation type.\n"; } } function O8b($O3q) { return "Could not create directory '$O3q'.\n"; } function O7z($l8c) { return "Please specify a value for the '$l8c' field.\n"; } function O8c($lp) { global $O68; return "Invalid database engine ('$lp').\nValid ones are: ".implode("' , '",$O68)."'\n"; } function l6c() { return "An error occurred when attempting to create the temporary directory '".TABLESDIR."' with the application's information.\n"; } function l6o($l31) { return "Could not create table '$l31' in the application's database.\n"; } function O6m($l31) { return "Could not drop table '$l31' from the application's database.\n"; } function O6c() { return "Check user permissions and try again.\n"; } function O6o($l8d) { return "<p>$l8d successfully deleted.</p>"; } function showmessage($O8d,$O55,$l8e) { global $O8e; if ($O8d !== "") $O8d= "($O8d) "; if ($O8e) { fwrite($O8e,strftime("%Y/%m/%d:%H:%M:%S",time())." ".strtoupper($O55).": $O8d $l8e"); } else { echo "<pre>".strtoupper($O55).": $O8d $l8e</pre>"; } } function O5c($O38) { global $O8e; if ($O8e) { $O37=print_r($O38,TRUE); fwrite($O8e,$O37); } else { print_r($O38); } }