<?php
/*
JSON_SQL_Bridge
Copyright 2016 Frank Vanden berghen
All Right reserved.

JSON_SQL_Bridge is not a free software. The JSON_SQL_Bridge software is NOT licensed under the "Apache License". 
If you are interested in distributing, reselling, modifying, contibuting or in general creating 
any derivative work from JSON_SQL_Bridge, please contact Frank Vanden Berghen at frank@timi.eu.
*/
namespace kibella; require_once __DIR__."/constants.php"; if (LOG) { global $O8h; $O8h=@fopen(LOGFILE,"a+"); } global $Ot; global $l6k; global $O54; global $l54; global $O9j; global $O5r; global $l93; global $O93; global $Obw; global $lbx; global $Obx; $Ot=array("sqlite" => O1r); $l6k=array_keys($Ot); $O6r=array(O18); $O54=array(O1r => O18,l1s => l19,O1s => l19); $l54=array(l1t => array(l1u => "(",O1u => ")",O1r => "select NAME from sqlite_master where lower(type) = 'table' and lower(name) = lower"),O1t => array(l1u => "(",O1u => ")",O1r => "PRAGMA table_info")); $O9j=array(l1v => array(O1r => "rowid"),O1v => array(O1r => "IFNULL"),l1w => array(O1r => "")); $O5r=array("s" => "second","m" => "minute","h" => "hour","d" => "day","w" => "week","M" => "month","y" => "year"); $O93=array(l2k => "avg",O2k => "count(distinct",MAX => "max",MIN => "min",O2l => "percentiles",l2m => "stddev",O2m => "sum",l2l => "count",); $Obw=array(l2k,O2k,l2l,MAX,MIN,O2l,O2m); $l93=array(O2n => array(NULL),l2o => array(array_values($Obw),O2n,O2o,l2p,O2v,O2w,l2x,O32),O2o => array(NULL,l31,O35,l3a),l2p => array(NULL,l31,O35,l3a),O2p => array(O2x,l2y),O2q => array(O2p,O2o,O2z),l2r => array(NULL),l2s => array(O2r,O2s),l2t => array(NULL),O2t => array(l3c,l3d,l3f),l2u => array(NULL),O2u => array(O36,O38,l39,O3a,l3b),l2v => array(O2q,O2z),O2v => array(O35,O3c),l2w => array(O3d),O2w => array(O35,O39,O3b),l2x => array(O35,O39),O2x => array(NULL,l2r,O2z),l2y => array(NULL,l2r,O2z),l2z => array(NULL,l34),O2z => array(l2v,l2t,l30),l30 => array(O33,O34,l35,l36,l3d),l31 => array(l37,O3e),O31 => array(O2n,l2w,O2z,l3e),l33 => array(O35),l32 => array(NULL),O32 => array(l2z,O35,l3e)); $lbx=array(l1z,O1z,l20,O20,l21,O21);