<?php
/*
JSON_SQL_Bridge 1.0
Copyright 2016 Frank Vanden berghen
All Right reserved.

JSON_SQL_Bridge is not a free software. The JSON_SQL_Bridge software is NOT licensed under the "Apache License". 
If you are interested in distributing, reselling, modifying, contibuting or in general creating 
any derivative work from JSON_SQL_Bridge, please contact Frank Vanden Berghen at frank@timi.eu.
*/
namespace kibella; if (LOG) { global $l8b; $l8b=@fopen(LOGFILE,"a+"); } global $l4b; global $O65; global $O4q; global $O4p; global $l9e; global $O5b; global $O8x; global $l8y; global $lbr; global $Obr; global $lbs; $l4b=array("sqlite" => O18,"sqlserver" => l19); $O65=array_keys($l4b); $l6e=array(O17); $O4q=array(O18 => O17,l19 => l18); $O4p=array(O19 => array(O1a => "(",l1b => ")",O18 => "select * from sqlite_master where lower(type) = 'table' and lower(name) = lower",l19 => "select * from MASTER.INFORMATION_SCHEMA.TABLES where upper(TABLE_TYPE) = 'BASE TABLE' and\n\t\t\t\t\t\t\t\tlower(TABLE_CATALOG) + '.' + lower(TABLE_SCHEMA) + '.' + lower(TABLE_NAME) = lower",),l1a => array(O1a => "(",l1b => ")",O18 => "PRAGMA table_info",l19 => "select COLUMN_NAME as name, DATA_TYPE as type from INFORMATION_SCHEMA.COLUMNS\n  \t\t\t\t\t\t\t\twhere lower(TABLE_CATALOG) + '.' + lower(TABLE_SCHEMA) + '.' + lower(TABLE_NAME) = lower"),); $l9e=array(O1b => array(O18 => "rowid",l19 => "row_number() over (order by (select null))",),l1c => array(O18 => "IFNULL",l19 => "ISNULL")); $O5b=array("s" => "second","m" => "minute","h" => "hour","d" => "day","w" => "week","M" => "month","y" => "year"); $l8y=array(l20 => "avg",O20 => "count(distinct",MAX => "max",MIN => "min",O21 => "percentiles",l22 => "stddev",O22 => "sum",l21 => "count",); $lbr=array(l20,O20,l21,MAX,MIN,O21,O22); $O8x=array(O23 => array(NULL),l24 => array(array_values($lbr),O23,O24,l25,O2b,O2c,l2d,O2i),O24 => array(NULL,l2h,O2l,l2q),l25 => array(NULL,l2h,O2l,l2q),O25 => array(O2d,l2e),O26 => array(O25,O24,O2f),l27 => array(NULL),l28 => array(O27,O28),l29 => array(NULL),O29 => array(l2s,l2t,l2v),l2a => array(NULL),O2a => array(O2m,O2o,l2p,O2q,l2r),l2b => array(O26,O2f),O2b => array(O2l,O2s),l2c => array(O2t),O2c => array(O2l,O2p,O2r),l2d => array(O2l,O2p),O2d => array(NULL,l27,O2f),l2e => array(NULL,l27,O2f),l2f => array(NULL,l2k),O2f => array(l2b,l29,l2g),l2g => array(O2j,O2k,l2l,l2m,l2t),l2h => array(l2n,O2u),O2h => array(O23,l2c,O2f,l2u),l2j => array(O2l),l2i => array(NULL),O2i => array(l2f,O2l,l2u)); $Obr=array(l1f,O1f,l1g,O1g,l1h,O1h);